swagger: "2.0"
info:
  description: "T社採用課題API"
  version: "1.0.0"
  title: "T社採用課題API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "example.com"
basePath: "/v1"
schemes:
- "http"
tags: 
  - name: API
paths:
  /:
    post:
      tags:
        - API
      description: "サーバ上にある画像へのPathを与えると、AI で分析し、その画像が所属する Class を返却する API があると します"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - in: "formData"
        name: "image_path"
        description: "サーバ上にある画像ファイルPath"
        required: true
        type: "string"
      responses:
        200:
          description: "成功"
          schema:
            $ref: "#/definitions/Success"
        405:
          description: "失敗"
          schema:
            $ref: "#/definitions/Failure"
definitions:
  Success:
    type: "object"
    properties:
      success:
        type: "boolean"
        example: true
      message:
        type: "string"
        example: "success"
      estimated_data:
        type: "object"
        properties:
          class:
            type: "integer"
            format: "int32"
            example: 3
          confidence:
            type: "number"
            format: "float"
            example: 0.8683
  Failure:
    type: "object"
    properties:
      success:
        type: "boolean"
        example: false
      message:
        type: "string"
        example: "Error:E50012"
      estimated_data:
        type: "object"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"